### ISSUE TITLE
Error itsdangerous== 2.1.0 version with Flask==1.1.2 

### ISSUE THREAD

**Issue by asiellb** [dOpensource/dsiprouter#418]
itsdangerous== 2.1.0 don´t work with Flask==1.1.2 

`Resetting credentials
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/dsiprouter/gui/util/security.py", line 10, in <module>
    from shared import updateConfig,StatusCodes
  File "/opt/dsiprouter/gui/shared.py", line 8, in <module>
    from flask import request, render_template, make_response, jsonify
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/dist-packages/itsdangerous/__init__.py)
Credentials have been updated
Setting credentials
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/opt/dsiprouter/gui/util/security.py", line 10, in <module>
    from shared import updateConfig,StatusCodes
  File "/opt/dsiprouter/gui/shared.py", line 8, in <module>
    from flask import request, render_template, make_response, jsonify
  File "/usr/local/lib/python3.7/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.7/dist-packages/itsdangerous/__init__.py)
Failed setting encrypted credentials`

Ref: https://github.com/pallets/itsdangerous/issues/290

Working with itsdangerous-2.0.1 version
